name: i_am_rich
description: "section 3"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# ⭐️ yaml의 child는 2번의 space가 있어야 함. 동일한 들어쓰기 레벨을 유지해야 함.
# 만약에 images 폴더 내 수십, 수백개의 asset이 있다고 했을 때, 모든 파일명을 작성해줄 수 없음
# 따라서 해당 폴더만 참조할 수 있도록 함 (아래와 같이 Images/ )
flutter:
  uses-material-design: true
  assets:
     - images/

